


// process.on('uncaughtException' , (err) => {
//     console.error("caught globally: ", err.message);
//     process.exit(1);
// });

// setTimeout(() => {
//     throw new Error("This is an uncught Exception");

// }, 2000);

















// what is the differrence between a caught and uncaught exception?
// why should we wxit the process after an uncaught exception?
// can you use try... catch to handle errors inside setTimeout? why or why not?
// what tool can you use in production to restart apps that crashes due to uncaught-exception?
